"use client";
import { useEffect, useRef, useState } from "react";
import { Camera, CameraOff, Hand, MessageSquare, Mic, MicOff, MonitorUp, MoreHorizontal, PhoneOff, Users } from "lucide-react";
import { REACTIONS, type ReactionType } from "@/components/meeting/meeting-ephemeral";
type Props = { microphoneEnabled: boolean; cameraEnabled: boolean; screenShareEnabled: boolean; screenSharePending: boolean; screenShareSupported: boolean; peopleOpen: boolean; chatOpen: boolean; participantCount?: number; isHost?: boolean; onMuteAll?: () => void; onAskAllToUnmute?: () => void; chatUnreadCount: number; handRaised: boolean; leaving: boolean; onToggleMicrophone: () => void; onToggleCamera: () => void; onToggleScreenShare: () => void; onTogglePeople: () => void; onToggleChat: () => void; onToggleHand: () => void; onReaction: (reaction: ReactionType) => void; onLeave: () => void };
export function MeetingControls(props: Props) {
  const [moreOpen, setMoreOpen] = useState(false); const { participantCount = 0, isHost = false, onMuteAll, onAskAllToUnmute, ...state } = props;
  const moreRootRef = useRef<HTMLSpanElement>(null);
  useEffect(() => {
    if (!moreOpen) return;
    const onPointerDown = (event: PointerEvent) => {
      if (!moreRootRef.current?.contains(event.target as Node)) setMoreOpen(false);
    };
    const onKeyDown = (event: KeyboardEvent) => { if (event.key === "Escape") setMoreOpen(false); };
    document.addEventListener("pointerdown", onPointerDown);
    document.addEventListener("keydown", onKeyDown);
    return () => { document.removeEventListener("pointerdown", onPointerDown); document.removeEventListener("keydown", onKeyDown); };
  }, [moreOpen]);
  const item = "relative inline-flex min-w-[56px] flex-col items-center justify-center gap-1 rounded-xl px-2 py-2 text-[10px] font-semibold text-slate-300 transition hover:bg-white/[.08] hover:text-white focus:outline-none focus:ring-2 focus:ring-cyan-300/60 sm:min-w-[66px]";
  const mic = <button type="button" onClick={state.onToggleMicrophone} aria-label={state.microphoneEnabled ? "Mute microphone" : "Unmute microphone"} className={`${item} ${!state.microphoneEnabled ? "text-red-200" : ""}`}>{state.microphoneEnabled ? <Mic className="size-5" /> : <MicOff className="size-5" />}<span>{state.microphoneEnabled ? "Mute" : "Unmute"}</span></button>;
  const camera = <button type="button" onClick={state.onToggleCamera} aria-label={state.cameraEnabled ? "Turn camera off" : "Turn camera on"} className={`${item} w-full min-w-0 whitespace-nowrap ${!state.cameraEnabled ? "text-red-200" : ""}`}>{state.cameraEnabled ? <Camera className="size-5" /> : <CameraOff className="size-5" />}<span>Camera</span></button>;
  const share = <button type="button" onClick={state.onToggleScreenShare} disabled={state.screenSharePending || !state.screenShareSupported} aria-label={state.screenShareSupported ? "Share screen" : "Screen sharing is not supported in this browser"} className={`${item} ${state.screenShareEnabled ? "bg-cyan-300/15 text-cyan-100" : ""} disabled:cursor-not-allowed disabled:opacity-50`}><MonitorUp className="size-5" /><span>Share</span></button>;
  const people = <button type="button" onClick={state.onTogglePeople} aria-expanded={state.peopleOpen} aria-controls="nexmeet-participants-panel" aria-label="Open participants" className={`${item} ${state.peopleOpen ? "bg-cyan-300/15 text-cyan-100" : ""}`}><Users className="size-5" /><span>People</span><b className="absolute right-1 top-1 min-w-4 rounded-full bg-cyan-300 px-1 text-[9px] leading-4 text-slate-950">{participantCount}</b></button>;
  const chat = <button type="button" onClick={state.onToggleChat} aria-expanded={state.chatOpen} aria-controls="nexmeet-chat-panel" aria-label="Open chat" className={`${item} ${state.chatOpen ? "bg-violet-300/15 text-violet-100" : ""}`}><MessageSquare className="size-5" /><span>Chat</span>{state.chatUnreadCount > 0 && <b className="absolute right-1 top-1 min-w-4 rounded-full bg-red-400 px-1 text-[9px] leading-4 text-slate-950">{state.chatUnreadCount > 9 ? "9+" : state.chatUnreadCount}</b>}</button>;
  const more = <span ref={moreRootRef} className="relative inline-flex"><button type="button" onClick={() => setMoreOpen((open) => !open)} aria-haspopup="menu" aria-expanded={moreOpen} aria-controls="nexmeet-more-menu" aria-label="Open more meeting actions" className={`${item} ${moreOpen ? "bg-cyan-300/15 text-cyan-100" : ""}`}><MoreHorizontal className="size-5" /><span>More</span></button>{moreOpen && <><button type="button" aria-label="Close more actions" className="fixed inset-0 z-[79] hidden bg-transparent sm:block" onClick={() => setMoreOpen(false)} /><div id="nexmeet-more-menu" role="menu" className="fixed inset-x-0 bottom-0 z-[80] rounded-t-3xl border border-white/10 bg-[#0b152b] p-4 pb-[max(1rem,env(safe-area-inset-bottom))] text-white shadow-2xl sm:absolute sm:inset-auto sm:bottom-[calc(100%+0.5rem)] sm:left-1/2 sm:w-64 sm:-translate-x-1/2 sm:rounded-2xl sm:p-3"><p className="px-2 pb-2 text-xs font-semibold uppercase tracking-widest text-slate-400">More actions</p><div className="grid grid-cols-5 gap-1">{REACTIONS.map((reaction) => <button key={reaction} type="button" role="menuitem" onClick={() => { state.onReaction(reaction); setMoreOpen(false); }} aria-label={`Send ${reaction} reaction`} className="rounded-xl px-2 py-2 text-xl hover:bg-white/10">{reaction}</button>)}</div><div className="mt-2 border-t border-white/10 pt-2">{isHost && <><p className="px-3 py-1 text-[10px] font-semibold uppercase tracking-widest text-cyan-300">Host controls</p><button type="button" role="menuitem" onClick={() => { onMuteAll?.(); setMoreOpen(false); }} className="flex w-full rounded-xl px-3 py-2 text-left text-sm text-slate-200 hover:bg-white/10">Mute all participants</button><button type="button" role="menuitem" onClick={() => { onAskAllToUnmute?.(); setMoreOpen(false); }} className="flex w-full rounded-xl px-3 py-2 text-left text-sm text-slate-200 hover:bg-white/10">Ask all to unmute</button></>}</div><button type="button" role="menuitem" onClick={() => { state.onLeave(); setMoreOpen(false); }} className="mt-1 flex w-full items-center gap-2 rounded-xl px-3 py-2 text-sm text-red-200 hover:bg-red-500/10 sm:hidden"><PhoneOff className="size-4" />Leave meeting</button><button type="button" role="menuitem" onClick={() => { state.onToggleHand(); setMoreOpen(false); }} className="mt-2 flex w-full items-center gap-2 rounded-xl px-3 py-2 text-sm text-slate-200 hover:bg-white/10"><Hand className="size-4" />{state.handRaised ? "Lower hand" : "Raise hand"}</button></div></>}</span>;
  const leave = <button type="button" onClick={state.onLeave} disabled={state.leaving} aria-label="Leave meeting" className="inline-flex min-w-[62px] flex-col items-center justify-center gap-1 rounded-xl bg-red-500 px-2 py-2 text-[10px] font-bold text-white shadow-lg shadow-red-950/30 transition hover:bg-red-400 focus:outline-none focus:ring-2 focus:ring-red-300/70 sm:min-w-[74px]"><PhoneOff className="size-5" /><span>{state.leaving ? "Leaving" : "Leave"}</span></button>;
  return <nav aria-label="Meeting controls" className="pointer-events-none absolute inset-x-0 bottom-0 z-50 flex h-[78px] items-center justify-center border-t border-white/[.08] bg-[#050a16]/95 px-1 pb-[env(safe-area-inset-bottom)] shadow-[0_-16px_40px_rgba(0,0,0,.3)] backdrop-blur-xl sm:px-5"><div className="pointer-events-auto relative grid w-full max-w-[1100px] grid-cols-[1fr_auto_1fr] items-center gap-3 sm:gap-6"><div className="hidden items-center justify-self-start gap-1 sm:flex">{mic}{camera}</div><div className="hidden items-center justify-self-center gap-1 lg:flex">{share}{people}{chat}{more}</div><div className="hidden items-center justify-self-end gap-1 sm:flex">{leave}</div><div className="grid min-w-0 w-full grid-cols-6 items-center justify-items-center gap-0 sm:hidden">{mic}{camera}{share}{people}{chat}{more}</div></div></nav>;
}
