"use client";
import { useState } from "react";
import { Check, Clock3, UserRound, X } from "lucide-react";
export type PendingWaitingRoomEntry = { entryId: string; displayName: string; requestedAt: string };
export function WaitingRoomHostPanel({ entries, onDecision }: { entries: PendingWaitingRoomEntry[]; onDecision: (entryId: string, decision: "admit" | "reject") => Promise<void> }) {
  const [busy, setBusy] = useState<string | null>(null); const [error, setError] = useState(""); const [reviewOpen, setReviewOpen] = useState(false);
  if (entries.length === 0) return null;
  async function decide(entryId: string, decision: "admit" | "reject") { if (busy) return; setBusy(entryId); setError(""); try { await onDecision(entryId, decision); } catch { setError("Unable to update this request. Please try again."); } finally { setBusy(null); } }
  const rows = <div className="grid gap-2 overflow-y-auto overscroll-contain p-3">{entries.map((entry) => <div key={entry.entryId} className="rounded-xl bg-white/[.05] p-3"><div className="flex items-center gap-3"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-gradient-to-br from-cyan-400/30 to-violet-500/40 text-sm font-bold">{entry.displayName.trim().slice(0, 1).toUpperCase()}</span><div className="min-w-0"><p className="truncate text-sm font-semibold text-white">{entry.displayName}</p><p className="mt-0.5 flex items-center gap-1 text-[11px] text-slate-400"><Clock3 className="size-3" />Ready to join</p></div></div><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={() => void decide(entry.entryId, "admit")} disabled={Boolean(busy)} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-cyan-400 px-3 py-2 text-xs font-bold text-slate-950 disabled:opacity-50"><Check className="size-3.5" />Admit</button><button type="button" onClick={() => void decide(entry.entryId, "reject")} disabled={Boolean(busy)} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-white/[.06] px-3 py-2 text-xs font-bold text-slate-200 hover:bg-red-500/20 disabled:opacity-50"><X className="size-3.5" />Reject</button></div></div>)}</div>;
  return <><div className="fixed bottom-[calc(5.25rem+env(safe-area-inset-bottom))] left-3 right-3 z-40 flex items-center justify-between rounded-xl border border-cyan-300/20 bg-[#0b152b]/95 px-3 py-2.5 text-white shadow-xl backdrop-blur-xl sm:left-auto sm:right-6 sm:w-[22rem]"><span className="flex items-center gap-2 text-xs font-semibold"><UserRound className="size-4 text-cyan-200" /><span aria-live="polite">{entries.length} {entries.length === 1 ? "person" : "people"} waiting</span></span><button type="button" onClick={() => setReviewOpen(true)} aria-label="Review waiting participants" className="rounded-lg bg-cyan-400 px-3 py-1.5 text-xs font-bold text-slate-950">Review</button></div>{reviewOpen && <div className="fixed inset-0 z-[70] bg-black/40 sm:bg-transparent" onClick={() => setReviewOpen(false)}><aside role="dialog" aria-modal="true" aria-label="Waiting room" onClick={(event) => event.stopPropagation()} className="absolute inset-x-0 bottom-0 max-h-[70dvh] overflow-hidden rounded-t-3xl border border-cyan-300/20 bg-[#0b152b] text-white shadow-[0_-20px_80px_rgba(0,0,0,.5)] sm:bottom-24 sm:left-auto sm:right-6 sm:w-[24rem] sm:rounded-2xl"><header className="flex items-center justify-between border-b border-white/[.08] px-5 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-xl bg-cyan-300/15 text-cyan-200"><UserRound className="size-4" /></span><div><h2 className="text-sm font-semibold">Waiting room</h2><p className="mt-0.5 text-xs text-slate-400">{entries.length} request{entries.length === 1 ? "" : "s"} to review</p></div></div><button type="button" onClick={() => setReviewOpen(false)} aria-label="Close waiting room" className="grid size-9 place-items-center rounded-lg text-slate-300 hover:bg-white/10"><X className="size-4" /></button></header><div className="max-h-[calc(70dvh-74px)] overflow-y-auto overscroll-contain">{rows}</div>{error && <p role="alert" className="px-4 pb-4 text-xs text-red-200">{error}</p>}</aside></div>}</>;
}
